import React, { useMemo, useState } from "react";

export default function MapScreen({ state, monthKey, summary }) {
  const [selectedDay, setSelectedDay] = useState(null);
  const [year, month] = monthKey.split("-").map(Number);
  const daysInMonth = new Date(year, month, 0).getDate();
  const firstWeekday = new Date(year, month - 1, 1).getDay();
  const cells = useMemo(() => [...Array(firstWeekday).fill(null), ...Array.from({ length: daysInMonth }, (_, i) => i + 1)], [firstWeekday, daysInMonth]);
  const record = selectedDay ? state.months[monthKey]?.days?.[selectedDay] || {} : null;
  return <div className="screen-content"><div className="screen-heading"><div><span className="date-line">{year}年{month}月</span><h2>冒险地图</h2></div><span className="map-score">{summary.earnedPoints} ★</span></div><section className="map-card"><div className="map-caption"><strong>本月坚持进度</strong><span>{Object.keys(state.months[monthKey]?.days || {}).length} 天有记录</span></div><div className="month-grid">{["日", "一", "二", "三", "四", "五", "六"].map((day) => <span className="weekday" key={day}>{day}</span>)}{cells.map((day, index) => { const key = day ? `${monthKey}-${String(day).padStart(2, "0")}` : `blank-${index}`; const done = day && Object.values(state.months[monthKey]?.days?.[key] || {}).some(Boolean); return <button key={key} className={day ? (done ? "calendar-day done" : "calendar-day") : "calendar-day blank"} onClick={() => day && setSelectedDay(key)} disabled={!day} aria-label={day ? `${day}日${done ? "已打卡" : "未打卡"}` : undefined}>{day || ""}</button>; })}</div></section><section className="section-block"><div className="section-title"><h3>月度目标</h3><span>{summary.earnedPoints}颗星星</span></div>{state.tasks.filter((task) => task.enabled).map((task) => { const value = task.kind === "manual" ? (summary.goals[task.id] ? "已达成" : "待记录") : task.kind === "streak" || task.kind === "piano" ? `${summary.streaks[task.id] || 0}天连续` : `${summary.counts[task.id] || 0}/${task.threshold}天`; return <div className="goal-row" key={task.id}><span className={summary.taskStatus[task.id] ? "goal-icon achieved" : "goal-icon"}>{summary.taskStatus[task.id] ? "✓" : "·"}</span><span><strong>{task.label}</strong><small>{task.description}</small></span><b>{value}</b></div>; })}</section>{selectedDay && <section className="selected-day"><strong>{selectedDay.slice(-2).replace(/^0/, "")}日完成记录</strong><span>{Object.entries(record).filter(([, value]) => value).map(([taskId]) => state.tasks.find((task) => task.id === taskId)?.label).join("、") || "这天还没有打卡"}</span></section>}</div>;
}
