import React, { useState } from "react";
import BackupControls from "../components/BackupControls.jsx";

const blankTask = { label: "", description: "", points: 1, kind: "count", threshold: 1, daily: true };
const blankReward = { label: "", description: "", points: 5 };

function makeId(prefix, label) { return `${prefix}-${label.trim().toLowerCase().replace(/[^a-z0-9\u4e00-\u9fff]+/g, "-") || Date.now()}`; }

export default function SettingsScreen({ state, onUpdate }) {
  const [panel, setPanel] = useState(null);
  const [taskDraft, setTaskDraft] = useState(blankTask);
  const [rewardDraft, setRewardDraft] = useState(blankReward);

  function patchTask(id, patch) { onUpdate({ ...state, tasks: state.tasks.map((task) => task.id === id ? { ...task, ...patch } : task) }); }
  function patchReward(id, patch) { onUpdate({ ...state, rewards: state.rewards.map((reward) => reward.id === id ? { ...reward, ...patch } : reward) }); }
  function addTask(event) { event.preventDefault(); if (!taskDraft.label.trim()) return; onUpdate({ ...state, tasks: [...state.tasks, { ...taskDraft, id: makeId("custom", taskDraft.label), points: Number(taskDraft.points), threshold: Number(taskDraft.threshold), enabled: true }] }); setTaskDraft(blankTask); }
  function addReward(event) { event.preventDefault(); if (!rewardDraft.label.trim()) return; onUpdate({ ...state, rewards: [...state.rewards, { ...rewardDraft, id: makeId("reward", rewardDraft.label), points: Number(rewardDraft.points), enabled: true }] }); setRewardDraft(blankReward); }
  function removeTask(id) { if (window.confirm("删除后这个任务不会再出现在新记录中，确定删除吗？")) onUpdate({ ...state, tasks: state.tasks.filter((task) => task.id !== id) }); }
  function removeReward(id) { if (window.confirm("删除后这个奖励不会再出现在商店中，确定删除吗？")) onUpdate({ ...state, rewards: state.rewards.filter((reward) => reward.id !== id) }); }

  return <div className="screen-content"><div className="screen-heading"><div><span className="date-line">规则管理</span><h2>设置</h2></div><span className="settings-count">{state.tasks.length}项任务</span></div>
    <section className="settings-list"><button className="settings-row settings-button" onClick={() => setPanel(panel === "tasks" ? null : "tasks")}><span><strong>任务管理</strong><small>新增、修改、停用或删除任务</small></span><b>{panel === "tasks" ? "⌃" : "›"}</b></button><button className="settings-row settings-button" onClick={() => setPanel(panel === "rewards" ? null : "rewards")}><span><strong>奖励管理</strong><small>调整星星商店的奖励</small></span><b>{panel === "rewards" ? "⌃" : "›"}</b></button><button className="settings-row settings-button" onClick={() => setPanel(panel === "archive" ? null : "archive")}><span><strong>月度归档</strong><small>查看以前的打卡记录</small></span><b>{panel === "archive" ? "⌃" : "›"}</b></button><button className="settings-row settings-button" onClick={() => setPanel(panel === "backup" ? null : "backup")}><span><strong>数据备份</strong><small>导出或导入本地 JSON</small></span><b>{panel === "backup" ? "⌃" : "›"}</b></button></section>
    {panel === "tasks" && <section className="editor-panel"><h3>任务管理</h3>{state.tasks.map((task) => <div className="edit-item" key={task.id}><div className="edit-fields"><input value={task.label} onChange={(e) => patchTask(task.id, { label: e.target.value })} aria-label={`${task.label}名称`} /><input value={task.description} onChange={(e) => patchTask(task.id, { description: e.target.value })} aria-label={`${task.label}标准`} /><label><input type="number" min="1" value={task.points} onChange={(e) => patchTask(task.id, { points: Number(e.target.value) })} /> 星</label></div><div className="edit-actions"><button className={task.enabled ? "tiny-button enabled" : "tiny-button"} onClick={() => patchTask(task.id, { enabled: !task.enabled })}>{task.enabled ? "使用中" : "已停用"}</button><button className="tiny-button danger" onClick={() => removeTask(task.id)}>删除</button></div></div>)}<form className="add-form" onSubmit={addTask}><strong>新增任务</strong><input placeholder="任务名称" value={taskDraft.label} onChange={(e) => setTaskDraft({ ...taskDraft, label: e.target.value })} /><input placeholder="达成标准" value={taskDraft.description} onChange={(e) => setTaskDraft({ ...taskDraft, description: e.target.value })} /><input type="number" min="1" placeholder="积分" value={taskDraft.points} onChange={(e) => setTaskDraft({ ...taskDraft, points: e.target.value })} /><button className="primary-button">添加任务</button></form></section>}
    {panel === "rewards" && <section className="editor-panel"><h3>奖励管理</h3>{state.rewards.map((reward) => <div className="edit-item" key={reward.id}><div className="edit-fields"><input value={reward.label} onChange={(e) => patchReward(reward.id, { label: e.target.value })} aria-label={`${reward.label}名称`} /><input value={reward.description} onChange={(e) => patchReward(reward.id, { description: e.target.value })} aria-label={`${reward.label}内容`} /><label><input type="number" min="1" value={reward.points} onChange={(e) => patchReward(reward.id, { points: Number(e.target.value) })} /> 星</label></div><div className="edit-actions"><button className={reward.enabled ? "tiny-button enabled" : "tiny-button"} onClick={() => patchReward(reward.id, { enabled: !reward.enabled })}>{reward.enabled ? "使用中" : "已停用"}</button><button className="tiny-button danger" onClick={() => removeReward(reward.id)}>删除</button></div></div>)}<form className="add-form" onSubmit={addReward}><strong>新增奖励</strong><input placeholder="奖励名称" value={rewardDraft.label} onChange={(e) => setRewardDraft({ ...rewardDraft, label: e.target.value })} /><input placeholder="奖励内容" value={rewardDraft.description} onChange={(e) => setRewardDraft({ ...rewardDraft, description: e.target.value })} /><input type="number" min="1" placeholder="所需积分" value={rewardDraft.points} onChange={(e) => setRewardDraft({ ...rewardDraft, points: e.target.value })} /><button className="primary-button">添加奖励</button></form></section>}
    {panel === "archive" && <section className="editor-panel"><h3>月度归档</h3>{Object.keys(state.months).sort().reverse().map((key) => <div className="archive-row" key={key}><strong>{key}</strong><span>{Object.keys(state.months[key].days || {}).length}天有记录</span><span>{state.months[key].archivedAt ? "已归档" : "当前月份"}</span></div>)}</section>}
    {panel === "backup" && <section className="editor-panel"><h3>数据备份</h3><p className="panel-hint">备份只保存在你的设备上，不会上传到网络。</p><BackupControls state={state} onImport={onUpdate} /></section>}
    <section className="tip-card"><strong>添加到苹果手机桌面</strong><p>在 Safari 打开后，点击分享按钮，再选择“添加到主屏幕”。以后可以像打开普通 App 一样使用。</p></section><p className="settings-note">当前版本：本地保存 · 无需密码 · 无需账号</p>
  </div>;
}
